# Generated by Django 5.2.5 on 2026-01-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={},
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='caption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='userpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_posts', to='blog.category'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
