# Generated by Django 5.2.5 on 2026-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userpostcomment_userpostlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
