# Generated by Django 5.2.5 on 2026-01-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userpost_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_at']},
        ),
    ]
