# Generated by Django 5.2.5 on 2025-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=20),
        ),
    ]
